@echo off

REM Data Science & Scientific Computing Libraries
echo Installing NumPy...
pip install numpy
echo Installing Pandas...
pip install pandas
echo Installing Matplotlib...
pip install matplotlib
echo Installing SciPy...
pip install scipy
echo Installing scikit-learn...
pip install scikit-learn
echo Installing TensorFlow...
pip install tensorflow
echo Installing Keras...
pip install keras
echo Installing PyTorch...
pip install torch
echo Installing Statsmodels...
pip install statsmodels

REM Web Development Libraries
echo Installing requests...
pip install requests
echo Installing Beautiful Soup...
pip install beautifulsoup4
echo Installing Scrapy...
pip install scrapy

REM Image Processing & OCR Libraries
echo Installing pytesseract...
pip install pytesseract

REM AI & Large Language Models Libraries
echo Installing openai...
pip install openai
echo Installing anthropic...
pip install anthropic

echo Installation complete.
pause
